import type { Metadata } from "next";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className="px-4
        [&>main]:grid
        [&>main]:gap-4
        [&>main]:py-4"
      >
        <Navigation />
        {children}
      </body>
    </html>
  );
}

function Navigation() {
  return (
    <nav className="print:hidden">
      <ul
        className="grid grid-cols-3 text-center
        [&>li>a]:before:absolute
        [&>li>a]:before:inset-0
        [&>li]:relative
        [&>li]:p-2"
      >
        <li>
          <a href="/">Beranda</a>
        </li>
        <li>
          <a href="/products">Produk</a>
        </li>
        <li>
          <a href="/receipts">Nota</a>
        </li>
      </ul>
    </nav>
  );
}
