import type { Metadata } from "next";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <nav>
          <ul>
            <li>
              <a href="/">Beranda</a>
            </li>
            <li>
              <a href="/products">Produk</a>
            </li>
            <li>
              <a href="/receipts">Nota</a>
            </li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
