import type { Metadata } from "next";

import "./globals.css";

import "./app.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="grid gap-4 p-4">
        <Navigation />
        {children}
      </body>
    </html>
  );
}

function Navigation() {
  return (
    <nav className="sticky top-4">
      <ul
        className="grid grid-flow-col gap-2 text-center
        [&>li>a]:before:absolute
        [&>li>a]:before:inset-0
        [&>li]:relative
        [&>li]:rounded
        [&>li]:bg-pink-300
        [&>li]:p-1"
      >
        <li>
          <a href="/">Beranda</a>
        </li>
        <li>
          <a href="/products">Produk</a>
        </li>
        <li>
          <a href="/receipts">Nota</a>
        </li>
      </ul>
    </nav>
  );
}
